server:
  port: 8080

spring:
  application:
    name: "hazel-topics-and-locks"

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.web: ERROR
    com.hazelcast: INFO
    com.alex.test: DEBUG

